### NumPy练习题1


In [1]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
n = np.zeros(10, dtype=np.int32)
n[4] = 1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [3]:
n = np.arange(10, 50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [4]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [5]:
n = np.random.random(size=(10, 10))
display(n, np.max(n), np.min(n))


array([[0.14278169, 0.69729804, 0.23283181, 0.81148805, 0.31593918,
        0.65633911, 0.62697368, 0.46310997, 0.5072308 , 0.50248595],
       [0.63484953, 0.25508884, 0.42360794, 0.42169708, 0.51946113,
        0.72082299, 0.12584005, 0.01828675, 0.95824625, 0.47129896],
       [0.5714925 , 0.17139193, 0.36913462, 0.67281653, 0.18638143,
        0.67494506, 0.70713475, 0.13410165, 0.06380612, 0.29723323],
       [0.03842016, 0.95859125, 0.22570293, 0.13927756, 0.51780809,
        0.25387241, 0.10163651, 0.36498453, 0.62911471, 0.7153982 ],
       [0.98882243, 0.39544182, 0.16020922, 0.61870992, 0.63683289,
        0.99315873, 0.43103009, 0.202104  , 0.35109174, 0.6251172 ],
       [0.93927477, 0.49044485, 0.17854587, 0.23659077, 0.23815232,
        0.16388948, 0.15708668, 0.6098227 , 0.67683088, 0.26537787],
       [0.33544719, 0.79761963, 0.18476831, 0.53390681, 0.29864119,
        0.64124869, 0.28420877, 0.63296651, 0.72907575, 0.57107494],
       [0.16413879, 0.30203191, 0.6006570

0.993158732258156

0.007300958763094667

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [6]:
n = np.zeros((10, 10), dtype=np.int16)
n[[0, -1]] = 1
n[:, [0, -1]] = 1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [7]:
n = np.ones((10, 10), dtype=np.int16)
n[1:-1, 1:-1] = 0
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

6、创建一个每一行都是从0到4的5*5矩阵

In [8]:
l = [0, 1, 2, 3, 4]
n = np.array(l*5).reshape((5, 5))
n

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [9]:
n = np.linspace(0, 1, 12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序


In [10]:
n = np.random.randint(0, 10, 10)
n.sort()
n[::-1]

array([9, 8, 8, 6, 5, 4, 3, 2, 2, 0])

9、创建一个长度为10的随机数组并将最大值替换为0


In [11]:
n = np.random.randint(0, 10, size=10)
display(n)

array([7, 3, 1, 3, 9, 3, 3, 2, 0, 5])

In [12]:
max1 = np.max(n)
max1

# 所有最大值对应的索引
max_indexs = np.argwhere(n==max1).reshape(-1)

n[max_indexs] = 0
n

array([7, 3, 1, 3, 0, 3, 3, 2, 0, 5])