### NumPy练习题2


In [3]:
import numpy as np

1、给定一个4维矩阵，如何得到最后两维的和？


In [5]:
n = np.random.randint(0, 10, size=(2, 3, 4, 5))
n
n.sum(axis=(2, 3))  
# 第1个维度是axis=0
# 第2个维度是axis=1
# 第3个维度是axis=2
# 第4个维度是axis=3

array([[86, 90, 85],
       [88, 88, 80]])

2、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？


In [9]:
n = np.arange(1, 6)
n2 = np.zeros(17, dtype=np.int16)
n2[ : : 4] = n
n2

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5], dtype=int16)

3、给定一个二维矩阵，如何交换其中两行的元素？


In [14]:
n = np.random.randint(0, 10, size=(4, 4))
display(n)

# 可以利用索引交换行
n2 = n[[1, 0, 2, 3]]
display(n2)

array([[7, 6, 8, 6],
       [3, 6, 4, 4],
       [8, 8, 3, 4],
       [3, 4, 0, 2]])

array([[3, 6, 4, 4],
       [7, 6, 8, 6],
       [8, 8, 3, 4],
       [3, 4, 0, 2]])

4、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间


In [17]:
n = np.random.randint(0, 10, size=100000)
# display(n)

%timeit np.power(n, 3)

299 µs ± 2.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%timeit n**3

312 µs ± 16.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


5、创建一个5 * 3随机矩阵和一个3 * 2随机矩阵，求矩阵积


In [19]:
n1 = np.random.randint(0, 100, size=(5, 3))
n2 = np.random.randint(0, 100, size=(3, 2))
np.dot(n1, n2)

array([[ 9897,  8924],
       [13383, 12856],
       [ 6845,  3792],
       [ 7305,  7240],
       [ 7423,  4584]])

6、矩阵的每一行的元素都减去该行的平均值


In [26]:
n = np.random.randint(0, 10, size=(3, 4))
display(n)

n2 = n.mean(axis=1).reshape(3, 1)
display(n2)

n - n2

array([[9, 6, 6, 0],
       [2, 4, 6, 9],
       [0, 8, 3, 4]])

array([[5.25],
       [5.25],
       [3.75]])

array([[ 3.75,  0.75,  0.75, -5.25],
       [-3.25, -1.25,  0.75,  3.75],
       [-3.75,  4.25, -0.75,  0.25]])

7、打印出以下矩阵（要求使用np.zeros创建8*8的矩阵）：

`
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
`

In [33]:
n = np.zeros((8, 8), dtype=int)
n[::2, 1::2] = 1
n[1::2, ::2] = 1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

8、正则化一个5*5随机矩阵
- 正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)


In [34]:
n = np.random.randint(0, 100, size=(5, 5))
display(n)

array([[99, 20, 42, 65, 67],
       [87, 43, 88, 22,  6],
       [65, 78, 29, 19, 37],
       [ 7, 60, 29, 84, 15],
       [83, 39, 36, 76, 94]])

In [36]:
min1 = n.min()
max1 = n.max()
min1, max1

(6, 99)

In [37]:
# 正则化后a = (a - min)/(max - min)
# 归一化: 0~1之间
(n - min1) / (max1 - min1)

array([[1.        , 0.15053763, 0.38709677, 0.6344086 , 0.65591398],
       [0.87096774, 0.39784946, 0.88172043, 0.17204301, 0.        ],
       [0.6344086 , 0.77419355, 0.24731183, 0.13978495, 0.33333333],
       [0.01075269, 0.58064516, 0.24731183, 0.83870968, 0.09677419],
       [0.82795699, 0.35483871, 0.32258065, 0.75268817, 0.94623656]])